---
name: CI
# JUST CHECKING PULL REQUESTS
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: linux_tweet_app
      PROJECT_ID: andiamo-1d849
      REPOSITORY: my-repo
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Authenticate with Google Cloud
      id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.SERVICE_ACOUNT_KEY }}'
  
    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker us-east1-docker.pkg.dev
      #gcloud auth configure-docker europe-docker.pkg.dev
        
    - name: When we have a pull event, we Build Docker Image and dont publish it.
      if: github.event_name == 'pull_request'
      run: 
        docker build -t $IMAGE_NAME:latest .
          
    - name: For every Commit, Tagging the image with the git commit hash and Push Docker Image to Artifact Registry
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      env: 
        COMMIT_TAG: ${{github.sha}}  
      run: |
        docker build -t $IMAGE_NAME:$COMMIT_TAG .
        docker tag $IMAGE_NAME:$COMMIT_TAG us-east1-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:$COMMIT_TAG
        docker push us-east1-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:$COMMIT_TAG
  # gcloud artifacts repositories create $REPOSITORY \
  # --repository-format=docker \
  # --location=us-east1
      shell: bash
    
    - name: For every git Tag, Build, Tag and publish Docker Image and push to Container Registry (GCR)
      if: github.ref == 'refs/tags/*' && github.event_name == 'create' || github.event_name == 'delete'
      env:
        GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
      run: |
        docker build -t $IMAGE_NAME:$GIT_TAG .
        docker tag $IMAGE_NAME:$GIT_TAG us-east1-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:$GIT_TAG
        docker push us-east1-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:$GIT_TAG
      shell: bash